apiVersion: apps/v1
kind: Deployment
metadata:
  name: dissco-digital-media-object-processor
  labels:
    app: dissco-digital-media-object-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dissco-digital-media-object-processor
  template:
    metadata:
      labels:
        app: dissco-digital-media-object-processor
    spec:
      containers:
        - name: dissco-digital-media-object-processor
          image: public.ecr.aws/dissco/dissco-core-digital-media-object-processor
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: spring.profiles.active
              value: web
            - name: spring.datasource.url
              value: jdbc:postgresql://database-1.cbppwfnjypll.eu-west-2.rds.amazonaws.com/dissco
            - name: springdoc.show-actuator
              value: "false"
            - name: spring.datasource.username
              valueFrom:
                secretKeyRef:
                  name: db-user-pass
                  key: username
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: db-user-pass
                  key: password
            - name: elasticsearch.hostname
              value: elasticsearch-master.default.svc.cluster.local
            - name: elasticsearch.port
              value: "9200"
            - name: elasticsearch.index-name
              value: digital-media-object
            - name: kafka.publisher.host
              value: kafka.kafka.svc.cluster.local:9092
            - name: kafka.consumer.host
              value: kafka.kafka.svc.cluster.local:9092
            - name: kafka.consumer.group
              value: group
            - name: kafka.consumer.topic
              value: digital-media-object
            - name: spring.security.oauth2.resourceserver.jwt.issuer-uri
              value: https://login-demo.dissco.eu/auth/realms/dissco
            - name: token.id
              value: demo-api-client
            - name: token.grantType
              value: client_credentials
            - name: token.tokenEndpoint
              value: https://login-demo.dissco.eu/auth/realms/dissco/protocol/openid-connect/token
            - name: token.secret
              valueFrom:
                secretKeyRef:
                  name: keycloak-client
                  key: keycloak-secret
            - name: endpoint.handle-endpoint
              value: https://sandbox.dissco.tech/handle-manager/api/v1/pids/
            - name: endpoint.token-endpoint
              value: https://login-demo.dissco.eu/auth/realms/dissco/protocol/openid-connect/token
          securityContext:
            runAsNonRoot: true