/*
 * This file is generated by jOOQ.
 */
package eu.dissco.core.digitalmediaobjectprocessor.database.jooq;


import eu.dissco.core.digitalmediaobjectprocessor.database.jooq.tables.Handles;
import eu.dissco.core.digitalmediaobjectprocessor.database.jooq.tables.NewDigitalMediaObject;
import eu.dissco.core.digitalmediaobjectprocessor.database.jooq.tables.NewDigitalSpecimen;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.handles</code>.
     */
    public static final Handles HANDLES = Handles.HANDLES;

    /**
     * The table <code>public.new_digital_media_object</code>.
     */
    public static final NewDigitalMediaObject NEW_DIGITAL_MEDIA_OBJECT = NewDigitalMediaObject.NEW_DIGITAL_MEDIA_OBJECT;

    /**
     * The table <code>public.new_digital_specimen</code>.
     */
    public static final NewDigitalSpecimen NEW_DIGITAL_SPECIMEN = NewDigitalSpecimen.NEW_DIGITAL_SPECIMEN;
}
