/*
 * This file is generated by jOOQ.
 */
package eu.dissco.core.digitalmediaobjectprocessor.database.jooq;


import eu.dissco.core.digitalmediaobjectprocessor.database.jooq.tables.DigitalMediaObject;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.digital_media_object</code>.
     */
    public static final DigitalMediaObject DIGITAL_MEDIA_OBJECT = DigitalMediaObject.DIGITAL_MEDIA_OBJECT;
}
